import { Module, TeamMember, Testimonial, Portfolio } from '@/types';

export const COMPANY_INFO = {
  name: 'Victify',
  tagline: 'Innovate. Build. Transform.',
  msmeNumber: 'UDYAM-TN-29-0091906',
  email: 'victify.offl@gmail.com',
  phone: '+91 63740 35585',
  address: 'Tiruvannamalai, Tamil Nadu, India',
  social: {
    linkedin: 'https://www.linkedin.com/company/victify/',
    twitter: 'https://twitter.com/victify',
    facebook: 'https://facebook.com/victify',
    instagram: 'https://instagram.com/victify',
  },
};

export const MODULES: Module[] = [
  {
    id: '1',
    module_number: 1,
    title: 'Python & Automation',
    description: 'Master Python fundamentals and automation techniques to streamline workflows and build powerful applications.',
    duration_weeks: 4,
    syllabus: [
      'Python Basics: Variables, Data Types, Control Flow',
      'Functions, Modules, and Packages',
      'Object-Oriented Programming in Python',
      'File Handling and Exception Management',
      'Web Scraping with BeautifulSoup and Selenium',
      'Automation Scripts and Task Scheduling',
      'Working with APIs and JSON',
      'Data Analysis with Pandas and NumPy',
    ],
    learning_outcomes: [
      'Write clean, efficient Python code following best practices',
      'Build automation scripts to handle repetitive tasks',
      'Scrape and process data from websites',
      'Work with external APIs and handle JSON data',
      'Analyze data using popular Python libraries',
    ],
    order_index: 1,
    image_url: '/assets/course-python.jpg',
  },
  {
    id: '2',
    module_number: 2,
    title: 'Full-Stack Development',
    description: 'Build modern, responsive web applications using cutting-edge frontend and backend technologies.',
    duration_weeks: 6,
    syllabus: [
      'HTML5, CSS3, and Responsive Design',
      'JavaScript ES6+ and DOM Manipulation',
      'React.js: Components, Hooks, and State Management',
      'Tailwind CSS and Modern UI Design',
      'Node.js and Express.js Backend Development',
      'RESTful API Design and Implementation',
      'Database Integration (PostgreSQL/MongoDB)',
      'Authentication and Authorization',
      'Deployment and Hosting',
    ],
    learning_outcomes: [
      'Create responsive, mobile-first web interfaces',
      'Build dynamic React applications with modern patterns',
      'Develop RESTful APIs with Node.js and Express',
      'Implement user authentication and security',
      'Deploy full-stack applications to production',
    ],
    order_index: 2,
    image_url: '/assets/course-fullstack.jpg',
  },
  {
    id: '3',
    module_number: 3,
    title: 'Software Development & Git',
    description: 'Learn professional software development practices, version control, and collaborative coding workflows.',
    duration_weeks: 3,
    syllabus: [
      'Git Fundamentals: Init, Add, Commit, Push',
      'Branching Strategies and Merge Workflows',
      'GitHub/GitLab: Pull Requests and Code Reviews',
      'Collaborative Development Best Practices',
      'CI/CD Pipeline Basics',
      'Testing: Unit Tests and Integration Tests',
      'Code Quality and Linting',
      'Agile Methodology and Scrum Framework',
    ],
    learning_outcomes: [
      'Master Git version control for professional development',
      'Collaborate effectively using GitHub workflows',
      'Write maintainable, testable code',
      'Understand and apply Agile development principles',
      'Set up basic CI/CD pipelines',
    ],
    order_index: 3,
    image_url: '/assets/course-git.jpg',
  },
  {
    id: '4',
    module_number: 4,
    title: 'Cloud & IT Infrastructure',
    description: 'Understand modern IT infrastructure, cloud computing platforms, and DevOps essentials.',
    duration_weeks: 4,
    syllabus: [
      'Cloud Computing Concepts and Service Models',
      'AWS/Azure Fundamentals',
      'Virtual Machines and Container Technology',
      'Docker: Images, Containers, and Compose',
      'Linux Command Line and Server Management',
      'Networking Basics: DNS, HTTP, SSL/TLS',
      'Database Administration and Backup Strategies',
      'Monitoring and Logging',
      'Security Best Practices',
    ],
    learning_outcomes: [
      'Deploy applications on cloud platforms (AWS/Azure)',
      'Containerize applications using Docker',
      'Manage Linux servers and perform basic administration',
      'Implement security and monitoring solutions',
      'Understand networking and infrastructure concepts',
    ],
    order_index: 4,
    image_url: '/assets/course-cloud.jpg',
  },
  {
    id: '5',
    module_number: 5,
    title: 'Capstone Project & Internship Simulation',
    description: 'Apply everything you have learned in a real-world project with mentorship and code reviews.',
    duration_weeks: 3,
    syllabus: [
      'Project Planning and Requirements Gathering',
      'System Design and Architecture',
      'Agile Sprint Planning and Execution',
      'Full-Stack Application Development',
      'Code Reviews and Refactoring',
      'Testing and Quality Assurance',
      'Documentation and Technical Writing',
      'Deployment and Production Readiness',
      'Project Presentation and Demo',
    ],
    learning_outcomes: [
      'Build a complete full-stack application from scratch',
      'Work in an Agile team environment',
      'Receive professional code reviews and feedback',
      'Deploy a production-ready application',
      'Present technical work to stakeholders',
    ],
    order_index: 5,
    image_url: '/assets/course-capstone.jpg',
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: '1',
    name: 'Prabhu Palani',
    role: 'Founder & CEO',
    bio: 'Visionary leader with 15+ years of experience in IT training and software development. Passionate about empowering the next generation of tech professionals.',
    image_url: '/assets/team-placeholder.jpg',
    order_index: 1,
  },
  {
    id: '2',
    name: 'Sathish P',
    role: 'Director of Software Development',
    bio: 'Expert software architect specializing in full-stack development and cloud solutions. Leads technical training programs and mentors aspiring developers.',
    image_url: '/assets/team-placeholder_variant_1.jpg',
    order_index: 2,
  },
  {
    id: '3',
    name: 'Sarathi S',
    role: 'Hiring Manager',
    bio: 'Talent acquisition specialist connecting skilled graduates with leading tech companies. Ensures our training aligns with industry demands.',
    image_url: '/assets/team-placeholder_variant_2.jpg',
    order_index: 3,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    role: 'Full-Stack Developer',
    company: 'Tech Solutions Ltd',
    content: 'Victify\'s training program transformed my career. The hands-on projects and expert mentorship gave me the confidence to land my dream job.',
    rating: 5,
    featured: true,
  },
  {
    id: '2',
    name: 'Priya Sharma',
    role: 'Software Engineer',
    company: 'Innovation Labs',
    content: 'The curriculum is perfectly aligned with industry needs. I learned practical skills that I use every day in my current role.',
    rating: 5,
    featured: true,
  },
  {
    id: '3',
    name: 'Arun Krishnan',
    role: 'DevOps Engineer',
    company: 'Cloud Systems Inc',
    content: 'Excellent training with real-world projects. The instructors are knowledgeable and always available to help. Highly recommended!',
    rating: 5,
    featured: true,
  },
];

export const PORTFOLIO: Portfolio[] = [
  {
    id: '1',
    title: 'Ambulance Management System',
    description: 'Real-time tracking, smart dispatching, and automated reports & billing for private ambulance services.',
    category: 'Automation System',
    technologies: ['React', 'Node.js', 'PostgreSQL', 'GPS API'],
    featured: true,
  },
  {
    id: '2',
    title: 'Clinic Patient Token & Queue Automation',
    description: 'Auto token generation, queue display system, and real-time patient flow management for clinics.',
    category: 'Healthcare Automation',
    technologies: ['React', 'Express', 'MongoDB', 'Socket.io'],
    featured: true,
  },
  {
    id: '3',
    title: 'E-Commerce Platform',
    description: 'Full-featured online shopping platform with payment integration and admin dashboard.',
    category: 'Web Application',
    technologies: ['Next.js', 'PostgreSQL', 'Stripe', 'Docker'],
    featured: false,
  },
];

export const SERVICES = [
  {
    id: '1',
    title: '⚙️ Automation Workflows',
    description: 'Smart automation to enhance efficiency and reduce manual effort.',
    icon: 'GraduationCap',
    image: '/assets/hero-training-classroom.jpg',
    features: [
      'Clinic automation',
      'Token & queue management',
      'Ambulance workflow automation',
      'Business process automation',
      'IoT & AI-powered solutions',
    ],
  },
  {
    id: '2',
    title: '🌐 Web Development',
    description: 'Custom digital solutions tailored for modern businesses.',
    icon: 'Code',
    image: '/assets/service-software-dev.jpg',
    features: [
      'Business & portfolio websites',
      'Enterprise web applications',
      'E-commerce platforms',
      'Admin dashboards',
      'API development & integration',
    ],
  },
  {
    id: '3',
    title: '🔍 Search Engine Optimization (SEO)',
    description: 'Grow your online presence with professional SEO strategies.',
    icon: 'Server',
    image: '/assets/service-infrastructure.jpg',
    features: [
      'On-page & technical SEO',
      'Off-page optimization',
      'Local SEO for Tiruvannamalai',
      'Google ranking improvement',
      'Keyword strategy & content optimization',
    ],
  },
  {
    id: '4',
    title: '📘 IT Training Programs',
    description: 'Job-ready training designed by industry professionals.',
    icon: 'GraduationCap',
    image: '/assets/hero-training-classroom_variant_1.jpg',
    features: [
      'Python & Automation',
      'Full-Stack Development',
      'Software Development & Git',
      'Cloud & IT Infrastructure',
      'Capstone Project & Internship Simulation',
    ],
  },
];
